-- Transaction rolls back every fixture. Requires migrations and local shim or Supabase Auth schema.
begin;
do $$
#variable_conflict use_variable
declare manager uuid:=gen_random_uuid(); staff uuid:=gen_random_uuid(); ingredient uuid; dish uuid; dish2 uuid; order_id uuid; order2 uuid;
 r jsonb; saved jsonb; p jsonb; v integer; tok text; c numeric; failed boolean;
begin
 begin insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values(gen_random_uuid(),'unmanaged-test@example.invalid','{}','{}'); set constraints all immediate; raise exception 'Public account insert was accepted'; exception when insufficient_privilege then null; end;
 insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values(manager,'manager-core@example.invalid','{"managed_account":true}','{"full_name":"Manager"}'),(staff,'staff-core@example.invalid','{"managed_account":true}','{"full_name":"Staff"}');
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 r:=public.sd_service('bootstrap_manager',jsonb_build_object('user_id',manager,'full_name','Manager'));
 update private.profiles set is_active=true where id=staff;
 perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',manager)::text,true);
 r:=public.sd_command('ingredient_create','{"name":"Flour test","unit":"g","reorder_level":"5"}','ingredient-a'); ingredient:=(r->>'id')::uuid;
 r:=public.sd_command('inventory_record',jsonb_build_object('ingredient_id',ingredient,'kind','purchase','quantity','100','unit_cost','2','reason','Initial purchase'),'purchase-a');
 r:=public.sd_command('inventory_record',jsonb_build_object('ingredient_id',ingredient,'kind','purchase','quantity','100','unit_cost','4','reason','Second purchase'),'purchase-b');
 select average_unit_cost into c from private.ingredients where id=ingredient; if c<>3 then raise exception 'Weighted average wrong: %',c; end if;
 r:=public.sd_command('menu_create','{"name":"Dish test","selling_price":"100","packaging_cost":"2"}','dish-a'); dish:=(r->>'id')::uuid;
 r:=public.sd_command('recipe_set',jsonb_build_object('id',dish,'expected_version',1,'ingredients',jsonb_build_array(jsonb_build_object('ingredient_id',ingredient,'quantity','10'))),'recipe-a');
 r:=public.sd_command('menu_create','{"name":"Dish second test","selling_price":"33.33","packaging_cost":"1"}','dish-b'); dish2:=(r->>'id')::uuid;
 r:=public.sd_command('recipe_set',jsonb_build_object('id',dish2,'expected_version',1,'ingredients',jsonb_build_array(jsonb_build_object('ingredient_id',ingredient,'quantity','1'))),'recipe-b');
 p:=jsonb_build_object('items',jsonb_build_array(jsonb_build_object('menu_item_id',dish,'quantity',2),jsonb_build_object('menu_item_id',dish2,'quantity',1)),'discount','10.01','platform_fee','3.01');
 r:=public.sd_command('order_create',p,'order-a'); order_id:=(r->>'id')::uuid;
 saved:=public.sd_command('order_create',p,'order-a'); if saved<>r then raise exception 'Idempotency did not return same result'; end if;
 begin perform public.sd_command('order_create',p||'{"discount":"11"}','order-a'); raise exception 'Changed payload accepted'; exception when unique_violation then null; end;
 select sum(discount_allocated) into c from private.order_items where order_items.order_id=order_id; if c<>10.01 then raise exception 'Discount allocation failed'; end if;
 select sum(fee_allocated) into c from private.order_items where order_items.order_id=order_id; if c<>3.01 then raise exception 'Fee allocation failed'; end if;
 r:=public.sd_command('order_transition',jsonb_build_object('id',order_id,'expected_version',1,'status','preparing'),'prepare-a');
 saved:=public.sd_command('order_transition',jsonb_build_object('id',order_id,'expected_version',1,'status','preparing'),'prepare-a');
 select stock_quantity into c from private.ingredients where id=ingredient; if c<>179 then raise exception 'Consumption/retry wrong: %',c; end if;
 begin perform public.sd_command('order_transition',jsonb_build_object('id',order_id,'expected_version',1,'status','ready'),'stale-a'); raise exception 'Stale version accepted'; exception when serialization_failure then null; end;
 r:=public.sd_command('order_transition',jsonb_build_object('id',order_id,'expected_version',2,'status','ready'),'ready-a');
 r:=public.sd_command('order_transition',jsonb_build_object('id',order_id,'expected_version',3,'status','completed'),'complete-a');
 r:=public.sd_read('analytics','{}'); if (r->>'net_revenue')::numeric<>223.32 or (r->>'contribution_margin')::numeric<>152.31 then raise exception 'Financial results wrong: %',r; end if;
 r:=public.sd_command('menu_update',jsonb_build_object('id',dish,'expected_version',2,'selling_price','200','packaging_cost','4'),'menu-edit');
 r:=public.sd_read('analytics','{}'); if (r->>'contribution_margin')::numeric<>152.31 then raise exception 'Historical margin changed'; end if;
 r:=public.sd_command('order_create',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('menu_item_id',dish,'quantity',1))),'order-b'); order2:=(r->>'id')::uuid;
 r:=public.sd_command('order_transition',jsonb_build_object('id',order2,'expected_version',1,'status','preparing'),'prepare-b');
 r:=public.sd_read('analytics','{}'); if (r->>'operating_profit')::numeric<>152.31 then raise exception 'Pending preparation incorrectly recognized'; end if;
 r:=public.sd_command('order_transition',jsonb_build_object('id',order2,'expected_version',2,'status','cancelled','reason','Customer cancellation'),'cancel-b');
 select stock_quantity into c from private.ingredients where id=ingredient; if c<>169 then raise exception 'Cancellation changed stock'; end if;
 r:=public.sd_read('analytics','{}'); if (r->>'cancellation_losses')::numeric<>34 then raise exception 'Cancellation loss wrong'; end if;
 r:=public.sd_command('inventory_record',jsonb_build_object('ingredient_id',ingredient,'kind','wastage','quantity','1','reason','Spillage'),'waste');
 r:=public.sd_command('expense_create',jsonb_build_object('category','rent','amount','10','incurred_on',(now() at time zone 'Asia/Karachi')::date),'expense-a');
 r:=public.sd_read('analytics','{}'); if (r->>'operating_profit')::numeric<>105.31 then raise exception 'Operating profit/double-count wrong %',r; end if;
 r:=public.sd_command('order_create',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('menu_item_id',dish,'quantity',100))),'order-short'); order2:=(r->>'id')::uuid;
 begin perform public.sd_command('order_transition',jsonb_build_object('id',order2,'expected_version',1,'status','preparing'),'prepare-short'); raise exception 'Insufficient stock accepted'; exception when serialization_failure then null; end;
 select stock_quantity into c from private.ingredients where id=ingredient; if c<>168 then raise exception 'Failed preparation changed stock'; end if;
 begin perform public.sd_command('user_update',jsonb_build_object('id',manager,'expected_version',2,'is_active',false),'deactivate-last'); raise exception 'Last manager deactivated'; exception when serialization_failure then null; end;
 r:=public.sd_command('review_token_create',jsonb_build_object('order_id',order_id),'token-a'); tok:=r->>'token';
 if exists(select 1 from private.audit_logs where after_data::text like '%'||tok||'%') then raise exception 'Review token leaked to audit'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',staff)::text,true);
 execute 'set local role authenticated';
 r:=public.sd_read('orders',jsonb_build_object('id',order_id)); if r::text like '%ingredient_cost%' or r::text like '%fee_allocated%' or r::text like '%packaging_cost%' then raise exception 'Staff cost disclosure'; end if;
 r:=public.sd_read('inventory',jsonb_build_object('id',ingredient)); if r ? 'average_unit_cost' then raise exception 'Staff average cost disclosure'; end if;
 begin perform public.sd_read('analytics','{}'); raise exception 'Staff read financial report'; exception when insufficient_privilege then null; end;
 begin perform public.sd_command('menu_update',jsonb_build_object('id',dish,'expected_version',3,'selling_price','1'),'staff-edit'); raise exception 'Staff menu edit allowed'; exception when insufficient_privilege then null; end;
 begin perform 1 from private.orders; raise exception 'Direct table read allowed'; exception when insufficient_privilege then null; end;
 begin perform public.sd_service('health','{}'); raise exception 'Staff called service'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update private.profiles set is_active=false where id=staff;
 begin perform public.sd_read('menu','{}'); raise exception 'Inactive user read allowed'; exception when insufficient_privilege then null; end;
 raise notice 'Core operational, accounting, idempotency and permission invariants passed';
end $$;
rollback;
