import Link from 'next/link';
import { ArrowRight, Check, ChefHat, ClipboardList, Users, UtensilsCrossed, Compass, Monitor, ShieldCheck } from 'lucide-react';
import { Brand } from '@/components/ui';
const portals = [
 {icon:Users,title:'Manager Console',tag:'EXECUTIVE',text:'Complete oversight of your daily service, restaurant team and menu.',items:['Create and manage staff accounts','Update dishes, prices and recipes','Follow every order through service','Keep ingredient stock under control'],path:'/manager'},
 {icon:ClipboardList,title:'Waiter Interface',tag:'FLOOR SERVICE',text:'Take care of every table, with your kitchen and dining room in sync.',items:['Build orders from the live menu','Add table notes and guest requests','Track preparation and pickup','Confirm when orders are served and paid'],path:'/waiter'},
 {icon:ChefHat,title:'Kitchen Board',tag:'CULINARY',text:'A clear, focused view of every ticket, from dispatch to the pass.',items:['See the incoming order queue','Start preparation with stock validation','Mark finished dishes ready for pickup','Keep cancellations visible to the team'],path:'/kitchen'},
];
export default function Home(){return <main className="landing stitch-landing">
 <nav><Link href="/"><Brand/></Link><div className="brand-nav"><a href="#overview" className="current">Overview</a><Link href="/manager">Manager Console</Link><Link href="/waiter">Floor Service</Link><Link href="/kitchen">Culinary Expediter</Link></div><Link className="button brand-access" href="/sign-in">Staff Access <ArrowRight size={14}/></Link></nav>
 <section className="symphony-hero" id="overview"><div className="architectural-rings" aria-hidden="true"><i/><i/><i/><i/></div><div className="symphony-content"><span className="hero-tag"><UtensilsCrossed size={14}/> RESTAURANT MANAGEMENT SYSTEM</span><h1>Masterful Symphony for Fine Dining Hospitality</h1><p>One unified platform for your entire restaurant — connecting the manager’s executive desk, floor service and culinary team.</p><div className="hero-buttons"><Link href="/sign-in" className="button bronze">Get Started Today <ArrowRight size={16}/></Link><a href="#portals-overview" className="button brand-access"><Compass size={16}/>Explore Portals</a></div><div className="hero-metrics"><div><strong>3</strong><span>DEDICATED ROLES</span><small>Manager, Waiter, Kitchen</small></div><div><strong>15s</strong><span>ORDER REFRESH</span><small>Shared updates across service stations</small></div><div><strong>One</strong><span>CONNECTED MENU</span><small>Recipes, availability and ingredient stock</small></div></div></div></section>
 <section className="editorial-strip"><div><span className="eyebrow">HAUTE CUISINE EFFICIENCY</span><h2>Where culinary artistry meets mathematical cadence.</h2><p>Bring orders, people and preparation together. Give every station the details it needs to deliver a thoughtful, well-timed dining experience.</p><div className="service-signature"><span><Users size={18}/></span><span><ChefHat size={18}/></span><span><Monitor size={18}/></span><div><strong>Synchronized Service Flow</strong><small>From the first order to the final course.</small></div></div></div><figure><img src="/images/stitch-chef.jpg" alt="Chef plating a dish in a restaurant kitchen"/><figcaption><b>Precision at the Pass</b><span>Every detail, in its place.</span></figcaption></figure><figure><img src="/images/stitch-dining.jpg" alt="Attentive restaurant dining room service"/><figcaption><b>Grace on the Floor</b><span>Hospitality with intention.</span></figcaption></figure></section>
 <section className="portals-section" id="portals-overview"><div className="section-intro"><span className="eyebrow">PURPOSE-BUILT WORKSPACES</span><h2>One System. Three Dedicated Portals.</h2><p>Each role has a space to focus, with one shared view of service.</p></div><div className="portal-cards">{portals.map(({icon:Icon,title,tag,text,items,path})=><article key={title}><div className="portal-card-top"><Icon size={24}/><span>{tag}</span></div><h3>{title}</h3><p>{text}</p><ul>{items.map(item=><li key={item}><Check size={13}/>{item}</li>)}</ul><Link href={path}>Open {title} <ArrowRight size={14}/></Link></article>)}</div></section>
 <section className="pipeline-section"><div className="section-intro"><span className="eyebrow">A CLEAR PATH THROUGH SERVICE</span><h2>Interactive Service Pipeline</h2><p>Explore the stages that connect the dining room with the kitchen.</p></div><div className="pipeline-frame"><div className="pipeline-bar"><span><Monitor size={16}/>SMART DINE / SERVICE WORKFLOW</span><Link href="/sign-in">Open your live workspace <ArrowRight size={14}/></Link></div><div className="pipeline-stages">{[{n:'01',title:'Order taken',body:'The waiter selects dishes and records the table’s requests.',tag:'PENDING'},{n:'02',title:'In preparation',body:'The kitchen starts the ticket and recipe ingredients are deducted.',tag:'PREPARING'},{n:'03',title:'Ready at the pass',body:'The kitchen marks the order ready for collection.',tag:'READY'},{n:'04',title:'Served & paid',body:'The waiter confirms the completed sale.',tag:'COMPLETED'}].map(s=><details key={s.n} open><summary><span>{s.n}</span>{s.title}</summary><p>{s.body}</p><small>{s.tag}</small></details>)}</div></div></section>
 <section className="hospitality-quote"><span>“</span><blockquote>Great hospitality is in the details.<br/>Give your team the clarity to make every one count.</blockquote><small>THE SMART DINE APPROACH</small></section>
 <section className="landing-cta"><ShieldCheck size={27}/><h2>Ready to Elevate Your Dining Operations?</h2><p>Your people, your kitchen and your floor — working together.</p><div className="hero-buttons"><Link href="/sign-in" className="button bronze">Sign In to Your Workspace <ArrowRight size={15}/></Link><Link href="/manager" className="button brand-access">Explore Manager Console</Link></div><small>MANAGER-CREATED ACCOUNTS · SECURE STAFF ACCESS</small></section>
 <footer><Brand/><span>Restaurant Management System</span><div><Link href="/manager">Manager</Link><Link href="/waiter">Floor Service</Link><Link href="/kitchen">Culinary</Link></div></footer>
</main>;}
